config/routes.rb
Coderobot::Application.routes.draw do
  resources :courses do
    resources :quizzes do
      resources :choices
    end
    resources :videos
    resources :exercises
  end
  resources :users
  post '/courses/:course_id/exercises/:exercise_id/check' => 'exercises#check'
  get '/courses/:course_id/exercises/:exercise_id/result' => 'exercises#result'
  post '/courses/:course_id/quizzes/:quiz_id/check' => 'quizzes#check'
  

  root :to => 'welcome#index'
  get "signup/index"

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :quiz
  attr_accessible :body, :index, :isAnswer
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :videos
  has_many :quizzes
  has_many :exercises
  attr_accessible :intro, :title
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :course
  attr_accessible :answer, :question ,:orderNum
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :course
  has_many :choices
  attr_accessible :answer, :title, :orderNum
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :fname, :lname, :password, :robotName, :email
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :course
  attr_accessible :description, :img, :order, :title, :url, :orderNum
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
	def new
	    @quiz = Quiz.find(params[:quiz_id])
		@choice = Choice.new
	end

	def show
 		@choice = Choice.find(params[:id])
	end

	def create
	    @quiz = Quiz.find(params[:quiz_id])
	    @choice = @quiz.choices.create(params[:choice])
	    redirect_to (:back)
	end
	def edit
	    @quiz = Quiz.find(params[:quiz_id])
  		@choice = Choice.find(params[:id])
	end
	def update
	    @quiz = Quiz.find(params[:quiz_id])
		@choice = Choice.find(params[:id])
		@choice.attributes = params[:choice]
		if @choice.save
			redirect_to (:back)
		else
			render 'edit'
		end
	end
	def destroy
	  @choice = Choice.find(params[:id])
	  @choice.destroy
	 
	  redirect_to (:back)
	end
	def index
		@course =Course.find(params[:course_id])
		@quiz = Quiz.find(params[:quiz_id])
		@choices = @quiz.choices.all
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def new
		@course =Course.new
	end
	def create
  		@course = Course.new(params[:course])
  		@course.save
  		redirect_to @course
	end
	def show
		@course = Course.find(params[:id])
	end
	def edit
		@course = Course.find(params[:id])
	end
	def update
		@course = Course.find(params[:id])
		@course.attributes = params[:course]
		if @course.save
			redirect_to @course
		else 
			render 'edit'
		end
	end
	def destroy
		@course = Course.find(params[:id])
		@course.destroy

		redirect_to @course
	end
	def index
		@courses = Course.all
	end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def new
	    @course = Course.find(params[:course_id])
		@exercise = Exercise.new
	end

	def show
 		@exercise = Exercise.find(params[:id])
	end

	def create
	    @course = Course.find(params[:course_id])
	    @exercise = @course.exercises.create(params[:exercise])
	    redirect_to course_exercises_path(@course)
	end
	def edit
	    @course = Course.find(params[:course_id])
  		@exercise = Exercise.find(params[:id])
	end
	def update
	    @course = Course.find(params[:course_id])
		@exercise = Exercise.find(params[:id])
		@exercise.attributes = params[:exercise]
		if @exercise.save
			redirect_to course_exercises_path(@course)
		else
			render 'edit'
		end
	end
	def check
		@course = Course.find(params[:course_id])
		@exercise =Exercise.find(params[:exercise_id])
		@attempt=params["attempt"]
		@answer = Exercise.find(params[:exercise_id]).answer
		if (@attempt === @answer)
			@result = true
			render 'result'
		else
			@result = false
			render 'result'
		end
	end
	def destroy
	  @exercise = Exercise.find(params[:id])
	  @exercise.destroy
	 
	  redirect_to course_exercise_path(@exercise)
	end
	def index
		@course = Course.find(params[:course_id])
		@exercises = @course.exercises.all
	end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
	def new
	    @course = Course.find(params[:course_id])
		@quiz = Quiz.new
	end

	def show
 		@quiz = Quiz.find(params[:id])
	end

	def create
	    @course = Course.find(params[:course_id])
	    @quiz = @course.quizzes.create(params[:quiz])
	    redirect_to course_quizzes_path(@course)
	end
	def edit
	    @course = Course.find(params[:course_id])
  		@quiz = Quiz.find(params[:id])
	end
	def check
		@course = Course.find(params[:course_id])
		@quiz =Quiz.find(params[:quiz_id])
		@choices = @quiz.choices
		@result = true
		@choices.each do |choice|
		 	if choice.isAnswer
		        if !params[choice.index.to_s()]
		        	@result = false
		        end
		    elsif params[choice.index.to_s()]
		    	@result = false
		    end
		end
	end
	def update
	    @course = Course.find(params[:course_id])
		@quiz = Quiz.find(params[:id])
		@quiz.attributes = params[:quiz]
		if @quiz.save
			redirect_to course_quizzes_path(@course)
		else
			render 'edit'
		end
	end
	def destroy
	  @quiz = Quiz.find(params[:id])
	  @quiz.destroy
	 
	  redirect_to course_quiz_path(@quiz)
	end
	def index
		@course = Course.find(params[:course_id])
		@quizzes = @course.quizzes.all
	end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user =User.new
	end
	def create
  		@user = User.new(params[:user])
  		@user.save
  		redirect_to @user
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		@user.attributes = params[:user]
		if @user.save
			redirect_to @user
		else 
			render 'edit'
		end
	end
	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to @user
	end
	def index
		@users = User.all
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def new
	    @course = Course.find(params[:course_id])
		@video = Video.new
	end

	def show
 		@video = Video.find(params[:id])
	end

	def create
	    @course = Course.find(params[:course_id])
	    @video = @course.videos.create(params[:video])
	    redirect_to course_videos_path(@course)
	end
	def edit
	    @course = Course.find(params[:course_id])
  		@video = Video.find(params[:id])
	end
	def update
	    @course = Course.find(params[:course_id])
		@video = Video.find(params[:id])
		@video.attributes = params[:video]
		if @video.save
			redirect_to course_videos_path(@course)
		else
			render 'edit'
		end
	end
	def destroy
	  @video = Video.find(params[:id])
	  @video.destroy
	 
	  redirect_to course_video_path(@video)
	end
	def index
		@course = Course.find(params[:course_id])
		@videos = @course.videos.all
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/choices/_choice.html.erb
<li>
  <input type="checkbox" name="<%= choice.index %>" value="<%= choice.index %>">
  <%= choice.body %>

</li>

app/views/choices/_form.html.erb
<%= form_for([:course,:quiz,@choice]) do |f| %>
  <p>
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :isAnswer %><br>
    <%= f.text_field :isAnswer %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choices</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', course_quiz_choices_path(@quiz) %>

app/views/choices/index.html.erb
<h1>Listing Choices</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Intro</th>
    <th>link</th>
  </tr>
 
  <% @choices.each do |choice| %>
    <tr>
      <td><%= choice.id %></td>
      <td><%= choice.index %></td>
      <td><%= choice.body %></td>
      <td><%= link_to "Detail",course_quiz_choice_path(:id =>choice.id) %></td>
    </tr>
  <% end %>
</table>

app/views/choices/new.html.erb
<h1>New Quiz</h1>
<%= render 'form' %>

app/views/choices/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @choice.index %>
</p>
 
<p>
  <strong>Intro:</strong>
  <%= @choice.body %>
</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:</h2>
    <ul>
    <% @use.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Intro</th>
    <th>link</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.fname %></td>
      <td><%= user.lname %></td>
      <td><%= link_to "Detail",user_path(:id =>user.id) %></td>
    </tr>
  <% end %>
</table>
<% content_for :head do %>
   <link rel="stylesheet" type="text/css" href="/assets/courses.css.scss" />
   <script type="text/javascript" src="/assets/jquery.min.js"></script>
   <link href="/assets/video-js.css" rel="stylesheet">
   <script src="/assets/video.js"></script>
    <link href="/assets/welcome/main.css" rel="stylesheet" type="text/css" />
<% end %>
<div align="center">
    <div id="header"><img src ="/assets/welcome/header_1.gif" border="0" usemap="#Map">
      <map name="Map" id="Map">
        <area shape="rect" coords="838,6,915,44" href="reg.html" />
        <area shape="rect" coords="924,11,985,43" href="login.html" />
      </map>
    </div>
  <div id="KeyVisual"><img src ="/assets/welcome/keyvisual.gif" border="0"></div>
    <div id="login_backgroud"><div style="background-image:url(/assets/welcome/login_background.gif); height:376px;">
    <div id="login_t">
      <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:</h2>
      <ul>
      <% @use.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
      <table border="0" cellspacing="0" cellpadding="0" background="/assets/welcome/login_pic.gif" height="162" width="380">
    <tr>
      <td width="22" height="41">&nbsp;</td>
      <td width="142" height="41">机器人名字</td>
      <td width="216" height="41"> 
        <%= f.text_field :fname %>
      </td>
      </tr>
    <tr>
      <td height="42">&nbsp;</td>
      <td height="42">用户名</td>
      <td height="42"> 
          <%= f.text_field :email %>
    </td>
      </tr>
    <tr>
      <td height="42">&nbsp;</td>
      <td height="42">密码</td>
      <td height="42">
        <%= f.text_field :password %>
      </td>
      </tr>
    <tr>
    <td colspan="3"><div align="center" style="color:#736d44">
      <%= f.submit '开始', :class => 'start_button'%></div></td>
    </tr>
    </table>
  <% end %>
</div>
</div>
</div>
  <div id="footer"><div align="left"><img src="/assets/welcome/about_us.gif"><img src="/assets/welcome/blog.gif"></div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :head do %>
   <link rel="stylesheet" type="text/css" href="/assets/courses.css.scss" />
   <script type="text/javascript" src="/assets/jquery.min.js"></script>
   <link href="/assets/video-js.css" rel="stylesheet">
   <script src="/assets/video.js"></script>
    <link href="/assets/welcome/main.css" rel="stylesheet" type="text/css" />
<% end %>
<div align="center">
    <div id="header"><img src ="/assets/welcome/header_1.gif" border="0" usemap="#Map">
      <map name="Map" id="Map">
        <area shape="rect" coords="838,6,915,44" href="reg.html" />
        <area shape="rect" coords="924,11,985,43" href="login.html" />
      </map>
    </div>
	<div id="KeyVisual"><img src ="/assets/welcome/keyvisual.gif" border="0"></div>
    <div id="login_backgroud"><div style="background-image:url(/assets/welcome/login_background.gif); height:376px;">
    <div id="login_t">
    	<%= form_for @user do |f| %>
	  <% if @user.errors.any? %>
	  <div id="errorExplanation">
	    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
	      this user from being saved:</h2>
	    <ul>
	    <% @use.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>
    	<table border="0" cellspacing="0" cellpadding="0" background="/assets/welcome/login_pic.gif" height="162" width="380">
	  <tr>
	    <td width="22" height="41">&nbsp;</td>
	    <td width="142" height="41">机器人名字</td>
	    <td width="216" height="41"> 
   			<%= f.text_field :fname %>
   		</td>
	    </tr>
	  <tr>
	    <td height="42">&nbsp;</td>
	    <td height="42">用户名</td>
	    <td height="42"> 
   		    <%= f.text_field :email %>
		</td>
	    </tr>
	  <tr>
	    <td height="42">&nbsp;</td>
	    <td height="42">密码</td>
	    <td height="42">
   			<%= f.text_field :password %>
   		</td>
	    </tr>
	  <tr>
    <td colspan="3"><div align="center" style="color:#736d44">
      <%= f.submit '开始', :class => 'start_button'%></div></td>
    </tr>
    </table>
	<% end %>
</div>
</div>
</div>
	<div id="footer"><div align="left"><img src="/assets/welcome/about_us.gif"><img src="/assets/welcome/blog.gif"></div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.fname%>

app/views/videos/_form.html.erb
<%= form_for([@course,@video]) do |f| %>
  <p>
    <%= f.label :orderNum %><br>
    <%= f.text_field :orderNum %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :img %><br>
    <%= f.text_field :img%>
  </p>
 
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/videos/_video.html.erb
<p>
  <%= video.title %>
  <div class="video"><a onClick="showVideo('<%= video.url %>')"><img width="100px" src="<%= video.img %>"></a></div>
</p>

app/views/videos/edit.html.erb
<h1>Editing Videos</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', course_videos_path(@course) %>

app/views/videos/index.html.erb
<h1>Listing Course</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Intro</th>
    <th>link</th>
  </tr>
 
  <% @videos.each do |video| %>
    <tr>
      <td><%= video.id %></td>
      <td><%= video.title %></td>
      <td><%= video.description %></td>
      <td><%= link_to "Detail",course_video_path(:id =>video.id) %></td>
    </tr>
  <% end %>
</table>

app/views/videos/new.html.erb
<h1>New Video</h1>
<%= render 'form' %>

app/views/videos/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>
 
<p>
  <strong>Intro:</strong>
  <%= @video.description %>
</p>
<p>
  <strong>Image:</strong>
  <%= @video.img %>
</p>
<p>
  <strong>URL:</strong>
  <%= @video.url %>
</p>