config/routes.rb
Coderobot::Application.routes.draw do
  resources :courses do
    resources :quizzes do
      resources :choices
    end
    resources :videos
    resources :exercises
  end
  resources :users
  post '/courses/:course_id/exercises/:exercise_id/check' => 'exercises#check'
  get '/courses/:course_id/exercises/:exercise_id/result' => 'exercises#result'
  post '/courses/:course_id/quizzes/:quiz_id/check' => 'quizzes#check'
  

  root :to => 'welcome#index'
  get "signup/index"

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :quiz
  attr_accessible :body, :index, :isAnswer
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :videos
  has_many :quizzes
  has_many :exercises
  attr_accessible :intro, :title
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :course
  attr_accessible :answer, :question ,:orderNum
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :course
  has_many :choices
  attr_accessible :answer, :title, :orderNum
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :fname, :lname, :password, :robotName, :email
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :course
  attr_accessible :description, :img, :order, :title, :url, :orderNum
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
	def new
	    @quiz = Quiz.find(params[:quiz_id])
		@choice = Choice.new
	end

	def show
 		@choice = Choice.find(params[:id])
	end

	def create
	    @quiz = Quiz.find(params[:quiz_id])
	    @choice = @quiz.choices.create(params[:choice])
	    redirect_to (:back)
	end
	def edit
	    @quiz = Quiz.find(params[:quiz_id])
  		@choice = Choice.find(params[:id])
	end
	def update
	    @quiz = Quiz.find(params[:quiz_id])
		@choice = Choice.find(params[:id])
		@choice.attributes = params[:choice]
		if @choice.save
			redirect_to (:back)
		else
			render 'edit'
		end
	end
	def destroy
	  @choice = Choice.find(params[:id])
	  @choice.destroy
	 
	  redirect_to (:back)
	end
	def index
		@course =Course.find(params[:course_id])
		@quiz = Quiz.find(params[:quiz_id])
		@choices = @quiz.choices.all
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def new
		@course =Course.new
	end
	def create
  		@course = Course.new(params[:course])
  		@course.save
  		redirect_to @course
	end
	def show
		@course = Course.find(params[:id])
	end
	def edit
		@course = Course.find(params[:id])
	end
	def update
		@course = Course.find(params[:id])
		@course.attributes = params[:course]
		if @course.save
			redirect_to @course
		else 
			render 'edit'
		end
	end
	def destroy
		@course = Course.find(params[:id])
		@course.destroy

		redirect_to @course
	end
	def index
		@courses = Course.all
	end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
	def new
	    @course = Course.find(params[:course_id])
		@quiz = Quiz.new
	end

	def show
 		@quiz = Quiz.find(params[:id])
	end

	def create
	    @course = Course.find(params[:course_id])
	    @quiz = @course.quizzes.create(params[:quiz])
	    redirect_to course_quizzes_path(@course)
	end
	def edit
	    @course = Course.find(params[:course_id])
  		@quiz = Quiz.find(params[:id])
	end
	def check
		@course = Course.find(params[:course_id])
		@quiz =Quiz.find(params[:quiz_id])
		@choices = @quiz.choices
		@result = true
		@choices.each do |choice|
		 	if choice.isAnswer
		        if !params[choice.index.to_s()]
		        	@result = false
		        end
		    elsif params[choice.index.to_s()]
		    	@result = false
		    end
		end
	end
	def update
	    @course = Course.find(params[:course_id])
		@quiz = Quiz.find(params[:id])
		@quiz.attributes = params[:quiz]
		if @quiz.save
			redirect_to course_quizzes_path(@course)
		else
			render 'edit'
		end
	end
	def destroy
	  @quiz = Quiz.find(params[:id])
	  @quiz.destroy
	 
	  redirect_to course_quiz_path(@quiz)
	end
	def index
		@course = Course.find(params[:course_id])
		@quizzes = @course.quizzes.all
	end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user =User.new
	end
	def create
  		@user = User.new(params[:user])
  		@user.save
  		redirect_to @user
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		@user.attributes = params[:user]
		if @user.save
			redirect_to @user
		else 
			render 'edit'
		end
	end
	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to @user
	end
	def index
		@users = User.all
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def new
	    @course = Course.find(params[:course_id])
		@video = Video.new
	end

	def show
 		@video = Video.find(params[:id])
	end

	def create
	    @course = Course.find(params[:course_id])
	    @video = @course.videos.create(params[:video])
	    redirect_to course_videos_path(@course)
	end
	def edit
	    @course = Course.find(params[:course_id])
  		@video = Video.find(params[:id])
	end
	def update
	    @course = Course.find(params[:course_id])
		@video = Video.find(params[:id])
		@video.attributes = params[:video]
		if @video.save
			redirect_to course_videos_path(@course)
		else
			render 'edit'
		end
	end
	def destroy
	  @video = Video.find(params[:id])
	  @video.destroy
	 
	  redirect_to course_video_path(@video)
	end
	def index
		@course = Course.find(params[:course_id])
		@videos = @course.videos.all
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <% if @course.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@course.errors.count, "error") %> prohibited
      this course from being saved:</h2>
    <ul>
    <% @course.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :intro %><br>
    <%= f.text_area :intro %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<% content_for :head do %>
   <link href="/assets/welcome/main.css" rel="stylesheet" type="text/css" />
<% end %>
<div align="center">
    <div id="header"><a href="/"><img src ="/assets/welcome/header_1.gif" border="0" usemap="#Map"></a>
      <map name="Map" id="Map">
        <area shape="rect" coords="838,6,915,44" href="reg.html" />
        <area shape="rect" coords="924,11,985,43" href="login.html" />
      </map>
    </div>
    <div id="KeyVisual"><img src ="/assets/welcome/keyvisual.gif" border="0"></div>
      <div id="login_backgroud"><div style="background-color:#718294; height:376px;">
        <div id="login_t">
          <table border="0" cellspacing="0" cellpadding="0" background="/assets/welcome/login_pic.gif" height="162" width="380">
          <tr>
            <td width="22" height="41">&nbsp;</td>
            <td width="142" height="41">机器人名字</td>
            <td width="216" height="41"><form id="form1" name="form1" method="post" action="">
              <label for="robotname"></label>
              <input type="text" name="robotname" id="robotname" />
            </form></td>
            </tr>
          <tr>
            <td height="42">&nbsp;</td>
            <td height="42">用户名</td>
            <td height="42"><form id="login" name="form1" method="post" action="">
              <label for="username"></label>
              <input type="text" name="username" id="username" />
            </form></td>
            </tr>
          <tr>
            <td height="42">&nbsp;</td>
            <td height="42">密码</td>
            <td height="42"><input type="password" name="password" id="password" /></td>
            </tr>
          <tr>
            <td colspan="3"><div align="center" style="color:#736d44"><%= link_to "开始",course_path(@courses[0]) %></div></td>
            </tr>
        </table>
      </div>
    </div>
  </div>
  <div id="footer"><div align="left"><img src="/assets/welcome/about_us.gif"><img src="/assets/welcome/blog.gif"></div>
  </div>
</div>

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
<% content_for :head do %>
   <link rel="stylesheet" type="text/css" href="/assets/courses.css.scss" />
   <script type="text/javascript" src="/assets/jquery.min.js"></script>
   <link href="/assets/video-js.css" rel="stylesheet">
   <script src="/assets/video.js"></script>
    <link href="/assets/welcome/main.css" rel="stylesheet" type="text/css" />
<% end %>
<script type="text/javascript" src="http://v3.jiathis.com/code/jiathis_r.js?uid=1364781260702316&move=0&amp;btn=r1.gif" charset="utf-8"></script>
<!-- JiaThis Button END -->
<div align="center">
    <div id="header"><a href="/"><img src ="/assets/welcome/header_1.gif" border="0" usemap="#Map"></a>
      <map name="Map" id="Map">
        <area shape="rect" coords="838,6,915,44" href="/users/new" />
        <area shape="rect" coords="924,11,985,43" href="/users" />
      </map>
    </div>
  <div id="video_login">
      <div id="quiz_panel">
        <a id="quiz_quit" onClick="hideQuiz();">close</a>
        <iframe id="quiz_iframe"></iframe>
      </div>
      <div id="video_login_source">
          <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="600" height="410" poster="/assets/welcome/my_video_poster.png">
         <source src="http://mov.bn.netease.com/movieMP4/2013/4/7/F/S8SCNR77F.mp4" type='video/mp4'>
        </video>
         <!-- <iframe id="videoUrl"></iframe>-->
      </div>
  </div>
  <div id="login_backgroud">
    <div id="login_content">
          <li><%=@course.title %> </li>
            <div class="list_li">
              <div id="materials">
               <% (1..@course.videos.length+@course.quizzes.length+@course.exercises.length).each do |i|%>
                <div id="task<%= i %>"></div>
                <% end %>
              </div>
            </div>
          </div>
</div>
  <div id="footer"><div align="left"><img src="/assets/welcome/about_us.gif"><img src="/assets/welcome/blog.gif"></div>
  </div>
</div>
<%= javascript_tag do %>
  current=1
  videos=<%=raw @course.videos.to_json %>;
  quizzes=<%=raw @course.quizzes.to_json %>;
  exercises=<%=raw @course.exercises.to_json %>;
<% end %>
<script type="text/javascript">
$(document).ready(function() { 
  hideQuiz();
  for (var i=0;i<videos.length;i++){
    var taskName="#task"+videos[i].orderNum;
    $(taskName).append(
    '<table width="700" border="0" cellpadding="0" cellspacing="0"><tr><td width="122" rowspan="2"><a href="javascript:showVideo('+i+')"><img src="/assets/course/icon_play.gif" width="64" height="51" /></a></td><td width="158"> <p>&nbsp;</p> <p>'+videos[i].title+'</p></td> <td width="176" height="28" align="center"><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /></td><td width="102">10</td><td width="142"><img src="/assets/course/thumb upBig-upNew.png" width="30" height="27" /></td></tr> <tr> <td width="158">15分钟 播放xx次</td> <td>你有<span class="Color_Yellow"> 3</span> 个好友观看了视频</td> <td width="102">20</td><td width="142"><img src="/assets/course/thumb upBig-DownNew.png" width="30" height="27" /></td></tr> </table>');
  }
   for (var i=0;i<quizzes.length;i++){
    var taskName="#task"+quizzes[i].orderNum;
   $(taskName).append(
    '<table width="700" border="0" cellpadding="0" cellspacing="0"><tr><td width="122" rowspan="2"><a href="javascript:showQuiz('+i+')"><img src="/assets/course/icon_next.gif" width="64" height="51" /></a></td><td width="158"> <p>&nbsp;</p> <p>小测验'+(i+1)+'</p></td> <td width="176" height="28" align="center"><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /></td><td width="102">10</td><td width="142"><img src="/assets/course/thumb upBig-upNew.png" width="30" height="27" /></td></tr> <tr> <td width="158">15分钟 播放xx次</td> <td>你有<span class="Color_Yellow"> 3</span> 个好友观看了视频</td> <td width="102">20</td><td width="142"><img src="/assets/course/thumb upBig-DownNew.png" width="30" height="27" /></td></tr> </table>');
  }
   for (var i=0;i<exercises.length;i++){
    var taskName="#task"+exercises[i].orderNum;
   $(taskName).append(
    '<table width="700" border="0" cellpadding="0" cellspacing="0"><tr><td width="122" rowspan="2"><a href="javascript:showExercise('+i+')"><img src="/assets/course/icon_next.gif" width="64" height="51" /></a></td><td width="158"> <p>&nbsp;</p> <p>玩代码'+(i+1)+'</p></td> <td width="176" height="28" align="center"><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /><img src="/assets/course/Star_FullSelected.png" width="20" height="18" /></td><td width="102">10</td><td width="142"><img src="/assets/course/thumb upBig-upNew.png" width="30" height="27" /></td></tr> <tr> <td width="158">15分钟 播放xx次</td> <td>你有<span class="Color_Yellow"> 3</span> 个好友观看了视频</td> <td width="102">20</td><td width="142"><img src="/assets/course/thumb upBig-DownNew.png" width="30" height="27" /></td></tr> </table>');
  }
});

function showNext(){
  for( var i=0;i<videos.length;i++){
    if(videos[i].orderNum==(current+1)){
      showVideo(i); 
    }
  } 
  for( var i=0;i<quizzes.length;i++){
    if(quizzes[i].orderNum==(current+1)){
      showQuiz(i);
    }
  }
  for( var i=0;i<exercises.length;i++){
    if(exercises[i].orderNum==(current+1)){
      showExercise(i);
    }
  }
  showLast()
}
function showLast(){
  console.log("finished");
}
function hideQuiz(){
  $("#quiz_panel").hide();
}
function showVideo(i){
  hideQuiz();
  var myPlayer = _V_("my_video_1");
   _V_("my_video_1").ready(function(){
      var myPlayer = this;
      myPlayer.src(videos[i].url);
      myPlayer.play();

    });
   current = videos[i].orderNum;
}
function showQuiz(i){
  $("#quiz_panel").show();
  $("#quiz_iframe").attr('src', '/courses/'+quizzes[i].course_id+'/quizzes/'+quizzes[i].id);
}
function showExercise(i){ 
  $("#quiz_panel").show();
  $("#quiz_iframe").attr('src', '/courses/'+exercises[i].course_id+'/exercises/'+exercises[i].id);
}
</script>

app/views/quizzes/_form.html.erb
<%= form_for([@course,@quiz]) do |f| %>
  <p>
    <%= f.label :orderNum %><br>
    <%= f.text_field :orderNum%>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/quizzes/_quiz.html.erb
<p>
  <div class="quiz"><a onClick="showQuiz('<%= quiz.id %>')"> <%= quiz.title %></a></div>
</p>

app/views/quizzes/check.html.erb
<% content_for :head do %>
   <link rel="stylesheet" type="text/css" href="/assets/exercises.css.scss" />
   <script type="text/javascript" src="/assets/jquery.min.js"></script>
<% end %>
<% if @result%>
<img width="400px" src="/assets/quiz/t.png">
<%else%>
<img width="400px" src="/assets/quiz/f.png">
<%end%>

app/views/quizzes/edit.html.erb
<h1>Editing Quizzes</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', course_quizzes_path(@course) %>

app/views/quizzes/index.html.erb
<h1>Listing Course</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Intro</th>
    <th>link</th>
  </tr>
 
  <% @quizzes.each do |quiz| %>
    <tr>
      <td><%= quiz.id %></td>
      <td><%= quiz.title %></td>
      <td><%= quiz.answer %></td>
      <td><%= link_to "Detail",course_quiz_path(:id =>quiz.id) %></td>
    </tr>
  <% end %>
</table>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>
<%= render 'form' %>

app/views/quizzes/show.html.erb
<% content_for :head do %>
    <link href="/assets/welcome/main.css" rel="stylesheet" type="text/css" />
<% end %>
<div id="quiz">
	<dt> <strong>选择题:</strong><%= @quiz.title %></dt>
<div id="quiz_content">
	<form action="/courses/<%= @quiz.course_id %>/quizzes/<%= @quiz.id%>/check" method="post">
		<ul>
			<%= render @quiz.choices %> 
		</ul>
		<button class="confirm">确定</button>
	</form>
</div>  

app/views/signup/index.html.erb
<h1>Signup Page</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.erb
<% content_for :head do %> 
	<link href="/assets/video-js.css" rel="stylesheet">
	<script src="/assets/video.js"></script>
  	<link href="/assets/welcome/main.css" rel="stylesheet" type="text/css" />
<% end %>
<div align="center">
    <div id="header"><img src ="/assets/welcome/header_1.gif" border="0" usemap="#Map">
      <map name="Map" id="Map">
        <area shape="rect" coords="838,6,915,44" href="/users/new" />
        <area shape="rect" coords="924,11,985,43" href="login.html" />
      </map>
    </div>
	<div id="video_login">
	<div id="video_login_source">
		<object width="600" height="400" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0">
		<param name="SRC" value="<%= asset_path("homepage_video.swf") %>">
		<embed src="<%= asset_path("homepage_video.swf") %>" width="600" height="400"></embed>
		</object>
	</div>
    </div>
	  <div id="login_backgroud">
	  	<div id="login_content">
	    	<div>
	        	<li>一个故事</li>
	            <dt>机器人a he机器人c 在星际旅行，发生意外。。。巴拉巴巴拉巴拉拉扒拉扒拉把涛把涛吧巴拉巴巴拉巴拉拉扒拉扒拉把涛把涛吧
	巴拉巴巴拉巴拉拉扒拉扒拉把涛把涛吧巴拉巴巴拉巴拉拉扒拉扒拉把涛把涛吧巴拉巴巴拉巴拉拉扒拉扒拉把涛把涛吧
	巴拉巴巴拉巴拉拉扒拉扒拉把涛把涛吧
	巴拉巴巴拉巴拉拉扒拉扒拉把涛把涛吧</dt>
	        </div>
	        <div><a href="/courses"><img src="/assets/welcome/action_now.gif" style="padding:20px;"></a></div>
	    </div>
	</div>
	<div id="footer"><div align="left"><img src="/assets/welcome/about_us.gif"><img src="/assets/welcome/blog.gif"></div>
  </div>
</div>